server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://<RDS엔드포인트>:3306/testdb # RDS 인스턴스 엔드포인트
    username: <RDS_마스터_사용자이름>             # RDS 마스터 사용자 이름
    password: <RDS_마스터_비밀번호>               # RDS 마스터 비밀번호
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  cloud:
    aws:
      credentials:
        access-key: <IAM_액세스키>                # IAM 통해 발급받은 액세스 키
        secret-key: <IAM_시크릿키>               # IAM 통해 발급받은 비밀 액세스 키
      s3:
        bucket: <S3_버킷명>                      # 생성한 버킷명
      region:
        static: ap-northeast-2

jwt:
  secret: 
  expiration: 360000
